"""
Polyhierarchy analysis charts for ICD-11 Foundation graph.

Generates:
  - poly_summary.png: Summary overview of polyhierarchy distribution (with sparklines)

Pareto charts are generated by generate_poly_pareto_v2.py.

All saved to analysis/minimaps/.
"""

import json
import os
from collections import Counter

import matplotlib.pyplot as plt
import numpy as np

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
BG_COLOR = "#1a1a2e"
TEXT_COLOR = "#e0e0e8"
GRID_COLOR = "#2a2a4a"
ACCENT_COLOR = "#8888aa"
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "minimaps")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Sequential warm colormap: 2 parents = mild orange, 9 = bright magenta
PARENT_COLORS = {
    2: "#c47a2a",
    3: "#d4622a",
    4: "#e04a30",
    5: "#e83545",
    6: "#ee2060",
    7: "#f00a7a",
    8: "#e800a0",
    9: "#d800c8",
}


def parent_color(pc: int) -> str:
    return PARENT_COLORS.get(pc, PARENT_COLORS[9])


# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
print("Loading graph data...")
with open(os.path.join(os.path.dirname(__file__), "foundation_graph.json")) as f:
    DATA = json.load(f)

all_ids = [k for k in DATA if k != "_meta"]
total_nodes = len(all_ids)
print(f"  {total_nodes} nodes loaded")

# ---------------------------------------------------------------------------
# Compute polyhierarchy metrics
# ---------------------------------------------------------------------------
poly_nodes = [
    (k, DATA[k]) for k in all_ids if len(DATA[k]["parents"]) > 1
]
poly_nodes.sort(key=lambda x: x[1]["descendantCount"], reverse=True)

print(f"  {len(poly_nodes)} polyhierarchy nodes")


def dup_cost(node: dict) -> int:
    """Extra tree rows created by additional parents."""
    return (len(node["parents"]) - 1) * (node["descendantCount"] + 1)


total_dup = sum(dup_cost(v) for _, v in poly_nodes)

# Parent count distribution
pc_counter = Counter(len(v["parents"]) for _, v in poly_nodes)

# Top 10 duplication cost
top10_dup = sum(dup_cost(v) for _, v in poly_nodes[:10])

# ---------------------------------------------------------------------------
# Matplotlib dark theme setup
# ---------------------------------------------------------------------------
plt.rcParams.update({
    "figure.facecolor": BG_COLOR,
    "axes.facecolor": BG_COLOR,
    "axes.edgecolor": ACCENT_COLOR,
    "axes.labelcolor": TEXT_COLOR,
    "text.color": TEXT_COLOR,
    "xtick.color": TEXT_COLOR,
    "ytick.color": TEXT_COLOR,
    "grid.color": GRID_COLOR,
    "grid.alpha": 0.6,
    "legend.facecolor": "#222244",
    "legend.edgecolor": ACCENT_COLOR,
    "legend.labelcolor": TEXT_COLOR,
    "font.size": 9,
})


# ===================================================================
# poly_summary.png — with descendant count sparklines
# ===================================================================
print("Generating poly_summary.png...")

pcs = sorted(pc_counter.keys())
counts = [pc_counter[pc] for pc in pcs]
colors = [parent_color(pc) for pc in pcs]
n_rows = len(pcs)

# Group duplication cost and descendant counts by parent count
dup_by_pc: dict[int, int] = {}
desc_by_pc: dict[int, list[int]] = {pc: [] for pc in pcs}
for _, v in poly_nodes:
    pc = len(v["parents"])
    dup_by_pc[pc] = dup_by_pc.get(pc, 0) + dup_cost(v)
    desc_by_pc[pc].append(v["descendantCount"])

# Sparkline bins (log-scale): 0, 1-5, 6-50, 51-500, 501-5K, 5K+
SPARK_BINS = [(0, 0), (1, 5), (6, 50), (51, 500), (501, 5000), (5001, None)]
SPARK_LABELS = ["0", "1-5", "6-50", "51-500", "501-5K", "5K+"]

def bin_descendants(desc_list: list[int]) -> list[int]:
    counts_out = [0] * len(SPARK_BINS)
    for d in desc_list:
        for bi, (lo, hi) in enumerate(SPARK_BINS):
            if hi is None:
                if d >= lo:
                    counts_out[bi] += 1
                    break
            elif lo <= d <= hi:
                counts_out[bi] += 1
                break
    return counts_out

# Layout: one subplot per parent-count row (for the sparkline), plus the main bar chart
fig, axes = plt.subplots(n_rows, 2, figsize=(10, 0.8 * n_rows + 1.5),
                         gridspec_kw={"width_ratios": [1.0, 0.7], "wspace": 0.3})

# --- Left column: main bar chart (spans all rows via a single axes) ---
# Remove individual left axes and draw on a single overlay
for r in range(n_rows):
    axes[r, 0].set_visible(False)

from matplotlib.transforms import Bbox
ax = fig.add_axes(Bbox.union([axes[0, 0].get_position(), axes[-1, 0].get_position()]))
ax.set_facecolor(BG_COLOR)

y_pos = np.arange(n_rows)
ax.barh(y_pos, counts, color=colors, edgecolor="none", alpha=0.9, height=0.65)

for i, (pc, count) in enumerate(zip(pcs, counts)):
    dup = dup_by_pc.get(pc, 0)
    label = f"  {count} nodes    +{dup:,} extra rows"
    ax.text(count + max(counts) * 0.02, i, label, va="center", fontsize=9, color=TEXT_COLOR)

ax.set_yticks(y_pos)
ax.set_yticklabels([f"{pc} parents" for pc in pcs], fontsize=10)
ax.set_xlabel("Number of nodes", fontsize=10)
ax.set_xlim(0, max(counts) * 1.8)
ax.grid(axis="x", linewidth=0.5)
ax.invert_yaxis()

# Summary text box
summary_lines = [
    f"Total nodes: {total_nodes:,}",
    f"Poly nodes: {len(poly_nodes):,} ({100 * len(poly_nodes) / total_nodes:.1f}%)",
    f"Extra rows: {total_dup:,}",
    f"Top 10 = {100 * top10_dup / total_dup:.0f}% of extra rows",
]
ax.text(
    0.97, 0.45, "\n".join(summary_lines),
    transform=ax.transAxes, fontsize=7.5,
    verticalalignment="top", horizontalalignment="right",
    bbox=dict(boxstyle="round,pad=0.4", facecolor="#222244", edgecolor=ACCENT_COLOR, alpha=0.9),
    family="monospace",
)

fig.suptitle("ICD-11 Foundation: Polyhierarchy Distribution",
             fontsize=12, fontweight="bold", y=0.98)

# --- Right column: sparkline per row ---
n_spark = len(SPARK_BINS)
# Use log scale for normalization: normalize within each row
for row_i, pc in enumerate(pcs):
    ax_s = axes[row_i, 1]
    ax_s.set_facecolor(BG_COLOR)
    binned = bin_descendants(desc_by_pc[pc])
    row_max = max(binned) if max(binned) > 0 else 1

    x_positions = np.arange(n_spark)
    bar_heights = np.array(binned, dtype=float)

    ax_s.bar(x_positions, bar_heights, width=0.8,
             color=colors[row_i], edgecolor="none", alpha=0.85)

    # Count labels on top of each bar
    for bi, cnt in enumerate(binned):
        if cnt > 0:
            ax_s.text(bi, cnt + row_max * 0.05, str(cnt),
                      ha="center", va="bottom", fontsize=6, color=TEXT_COLOR, alpha=0.8)

    ax_s.set_ylim(0, row_max * 1.35)
    ax_s.set_xlim(-0.5, n_spark - 0.5)

    # Only show x labels on the bottom row
    if row_i == n_rows - 1:
        ax_s.set_xticks(x_positions)
        ax_s.set_xticklabels(SPARK_LABELS, fontsize=6, rotation=30, ha="right")
    else:
        ax_s.set_xticks([])

    ax_s.set_yticks([])
    for spine in ax_s.spines.values():
        spine.set_visible(False)

# Title for sparkline column
axes[0, 1].set_title("Descendant count", fontsize=9, pad=6, color=TEXT_COLOR)

fig.tight_layout()
fig.savefig(os.path.join(OUTPUT_DIR, "poly_summary.png"), dpi=100, facecolor=BG_COLOR)
plt.close(fig)
print("  Saved poly_summary.png")


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print(f"\nAll charts saved to {OUTPUT_DIR}/")
for fname in sorted(os.listdir(OUTPUT_DIR)):
    fpath = os.path.join(OUTPUT_DIR, fname)
    if os.path.isfile(fpath):
        kb = os.path.getsize(fpath) / 1024
        marker = " <-- NEW" if fname.startswith("poly_") else ""
        print(f"  {fname:35s}  {kb:7.1f} KB{marker}")
